import { DeviceProfile, DeviceProfileId } from '../../types/preview';

export const DEVICE_PROFILES: Record<DeviceProfileId, DeviceProfile> = {
  'pixel-8': {
    id: 'pixel-8',
    name: 'Google Pixel 8',
    category: 'phone',
    widthDp: 360,
    heightDp: 780,
    borderRadius: '44px',
    bezelWidth: '10px',
    hasCameraCutout: true,
    cutoutType: 'punchhole',
  },
  'galaxy-s24': {
    id: 'galaxy-s24',
    name: 'Galaxy S24 Ultra',
    category: 'phone',
    widthDp: 384,
    heightDp: 824,
    borderRadius: '16px',
    bezelWidth: '8px',
    hasCameraCutout: true,
    cutoutType: 'punchhole',
  },
  foldable: {
    id: 'foldable',
    name: 'Galaxy Fold (Unfolded)',
    category: 'foldable',
    widthDp: 672,
    heightDp: 740,
    borderRadius: '24px',
    bezelWidth: '10px',
    hasCameraCutout: true,
    cutoutType: 'punchhole',
  },
  'tablet-10': {
    id: 'tablet-10',
    name: 'Pixel Tablet (10.9")',
    category: 'tablet',
    widthDp: 800,
    heightDp: 1200,
    borderRadius: '28px',
    bezelWidth: '14px',
    hasCameraCutout: true,
    cutoutType: 'tablet-camera',
  },
  frameless: {
    id: 'frameless',
    name: 'Frameless (Clean Canvas)',
    category: 'frameless',
    widthDp: 360,
    heightDp: 740,
    borderRadius: '12px',
    bezelWidth: '1px',
    hasCameraCutout: false,
  },
};
