build:
  maxIssues: 0
  excludeCorrectable: false

complexity:
  active: true
  CyclomaticComplexMethod:
    active: true
    threshold: 15
  LongMethod:
    active: true
    threshold: 60
  LongParameterList:
    active: true
    functionThreshold: 6
    constructorThreshold: 7
  TooManyFunctions:
    active: true
    thresholdInFiles: 25
    thresholdInClasses: 25
    thresholdInInterfaces: 25
    thresholdInObjects: 25
    thresholdInEnums: 25

empty-blocks:
  active: true
  EmptyCatchBlock:
    active: true
    allowedExceptionNameRegex: "^(_|(ignore|expected).*)"
  EmptyFunctionBlock:
    active: true
  EmptyFinallyBlock:
    active: true
  EmptyIfBlock:
    active: true
  EmptyWhileBlock:
    active: true

exceptions:
  active: true
  TooGenericExceptionCaught:
    active: true
    exceptionNames:
      - ArrayIndexOutOfBoundsException
      - Error
      - Exception
      - IllegalMonitorStateException
      - NullPointerException
      - IndexOutOfBoundsException
      - RuntimeException
      - Throwable
  SwallowedException:
    active: true

potential-bugs:
  active: true
  UnsafeCallOnNullableType:
    active: true
  EqualsAlwaysReturnsTrueOrFalse:
    active: true
  InvalidRange:
    active: true
  UnconditionalJumpStatementInLoop:
    active: true

style:
  active: true
  MaxLineLength:
    active: true
    maxLineLength: 120
    excludePackageStatements: true
    excludeImportStatements: true
    excludeCommentStatements: false
  WildcardImport:
    active: true
  UnusedImports:
    active: true
  ReturnCount:
    active: true
    max: 4
  UnusedPrivateMember:
    active: true
  VarCouldBeVal:
    active: true

formatting:
  active: true
  android: false
  autoCorrect: false
  Indentation:
    active: true
    indentSize: 4
  MaximumLineLength:
    active: true
    maxLineLength: 120
  NoWildcardImports:
    active: true
  FinalNewline:
    active: true
